name: PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "Pull Request Linting"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: oven-sh/setup-bun@v1
      - name: "Install Dependencies"
        run: bun install
      - name: "Run Linter"
        run: bun run test
      - name: "Test"
      # remove after Bun test done
        run: bun run test-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
