on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Pull Request Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - name: Setup NodeJS 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "pnpm"
      - name: "Install Dependencies"
        run: pnpm -recursive install
      - name: "Test Building"
        run: pnpm run build
      - name: "Run Linter"
        run: pnpm run lint:fix
      - name: "Format Code"
        run: pnpm run format
