name: PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Pull Request Linting"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v2.2.4
      - name: Setup NodeJS 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: "Install Dependencies"
        run: pnpm -recursive install
      - name: "Test Building"
        run: pnpm run build
      - name: "Run Linter"
        run: pnpm run lint:fix
      - name: "Format Code"
        run: pnpm run format
      - name: "Commit Changes"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: :art: Lint and Format"
