name: Create Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: bun install
      - name: Lint
        run: bun lint
      - name: Build
        run: bun run build
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: 'chore(release): :ship: Version Package'
          title: 'Version Package'
          version: bun run version
          publish: bun run release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
