name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - name: Setup NodeJS 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: "Install Dependencies"
        run: pnpm -recursive install
      - name: Build Project
        run: pnpm run build
      - name: Get Version Tag
        id: version
        uses: ncipollo/semantic-version-action@v1.0.1
      - name: Create Zipped Artifact
        run: |
          cd dist/
          zip -r ../fbl-fvtt_${{ steps.version.outputs.tag }}.zip *
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "fbl-fvtt_${{ steps.version.outputs.tag }}.zip"
          generateReleaseNotes: true
