name: Create Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Create Release or Version
        uses: changesets/action@63b1daab35bf3f61ec8ebb5fefb539f2e735a82a
        with:
          commit: 'chore(release): Version Package'
          title: 'Version Package'
          version: bun run version
          publish: bun run release
          createGithubReleases: true
          createPrAsDraft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
